### ISSUE TITLE
Can't import the assets I've purchased

### ISSUE THREAD

**Issue by bouiboui** [sketchfab/unity-plugin#4]
It works great with free assets, but it would be a lot more useful if I could download the assets I've purchased as well.
Wondering if it's on your roadmap ?

**Comment by AurL** [comment]
Hi @bouiboui 
Yes, having access to purchased assets from the plugin is definitely in the roadmap, even if there is still no clear ETA yet

**Comment by bouiboui** [comment]
That's great, thank you!
